### ISSUE TITLE
This should be "plug and play" right?

### ISSUE THREAD

**Issue by DkVagabonden** [Rene-Sackers/gta-network-fuel#1]
I've tried to install this but i get javascripts errors. 

Had to make the main.js and fuelAPI.js files myself since they have been deleted? is this correct or?

If you have time, please write a small guide to install this, i most be doing something wrong. 
(It does create the "VehicleFuelSpecifications.xml" and update it)..

**Comment by Rene-Sackers** [comment]
Sorry for the late reply.
It's not done yet. You can't refuel vehicles yet.
But if you know someone who's willing to work on it a little further, I'm open for pull requests :)
